services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - envs/mysql.env

  redis:
    container_name: tcc_control_redis
    restart: always
    image: redis:6.0.20-alpine3.18
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

  django:
    build: ./django
    volumes:
      - ./django/:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=tcc_control.settings.dev
    env_file:
      - envs/mysql.env
      - envs/email.env
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data:
