services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - envs/mysql.env

  django:
    build: ./django
    volumes:
      - ./django/:/code
    ports:
      - "8000:8000"
    env_file:
      - envs/mysql.env
    depends_on:
      - mysql

volumes:
  mysql_data:
