# Generated by Django 4.2 on 2023-06-11 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fields', models.JSONField(verbose_name='Fields')),
                ('template_abnt', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Activity Configuration',
                'verbose_name_plural': 'Activity Configurations',
            },
        ),
    ]
