# Generated by Django 4.2 on 2023-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityconfiguration',
            name='template_abnt',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
