# Generated by Django 4.2 on 2023-06-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityconfiguration',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
    ]
