# Generated by Django 4.2 on 2023-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activityconfiguration_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityconfiguration',
            name='template_abnt',
        ),
        migrations.AddField(
            model_name='activityconfiguration',
            name='document_insertion',
            field=models.BooleanField(default=True, verbose_name='Document insertion'),
        ),
    ]
