# Generated by Django 4.2 on 2023-06-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activityconfiguration_template_abnt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityconfiguration',
            options={'verbose_name': 'Activity Configuration', 'verbose_name_plural': 'Activity Configurations'},
        ),
    ]
