# Generated by Django 4.2 on 2023-10-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rgm',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RGM'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='courses.course', verbose_name='University course'),
        ),
    ]
