# Generated by Django 4.2 on 2023-09-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rgm',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RGM'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_course',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='university course'),
        ),
    ]
