# Generated by Django 4.2 on 2023-06-09 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='pariticipants'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='teacher'),
        ),
    ]
