# Generated by Django 4.2 on 2023-06-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
    ]
