# Generated by Django 4.2 on 2023-07-01 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_timetable_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageexample',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_examples', to='timetables.stage', verbose_name='stage'),
        ),
    ]
