# Generated by Django 4.2 on 2023-06-10 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/step-example/')),
            ],
        ),
    ]
