# Generated by Django 4.2 on 2023-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_stepexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='presentation_date',
            field=models.DateField(blank=True, null=True, verbose_name='presentation date'),
        ),
    ]
