# Generated by Django 4.2 on 2023-10-08 18:18

from django.db import migrations, models
import timetables.documents


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_stageexample_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='document_template',
            field=models.FileField(blank=True, upload_to=timetables.documents.get_template_folder, verbose_name='Document template'),
        ),
    ]
