# Generated by Django 4.2 on 2023-06-10 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('participants', models.ManyToManyField(related_name='meeting_participants', through='meetings.ApprovedMeeting', to=settings.AUTH_USER_MODEL)),
                ('work_step', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='step_meeting', to='works.workstep', verbose_name='work step')),
            ],
        ),
        migrations.AddField(
            model_name='approvedmeeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_approved', to='meetings.meeting', verbose_name='meeting'),
        ),
        migrations.AddField(
            model_name='approvedmeeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_meeting', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
