# Generated by Django 4.2 on 2023-06-13 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meeting_participants', through='meetings.ApprovedMeeting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='work_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='step_meeting', to='works.workstep', verbose_name='work step'),
        ),
        migrations.AddField(
            model_name='approvedmeeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_approved', to='meetings.meeting', verbose_name='meeting'),
        ),
        migrations.AddField(
            model_name='approvedmeeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_meeting', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
