# Generated by Django 4.2 on 2023-07-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(null=True, verbose_name='meeting date'),
        ),
        migrations.AlterField(
            model_name='approvedmeeting',
            name='approved',
            field=models.BooleanField(default=None, null=True, verbose_name='approved'),
        ),
    ]
