# Generated by Django 4.2 on 2023-09-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_meeting_date_alter_approvedmeeting_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='developed_activities',
            field=models.TextField(default='', verbose_name='Developed activities'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='instructions',
            field=models.TextField(default='', verbose_name='Instructions'),
        ),
    ]
