# Generated by Django 4.2 on 2023-09-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_developed_activities_meeting_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='developed_activities',
            field=models.TextField(blank=True, default='', verbose_name='Developed activities'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='instructions',
            field=models.TextField(blank=True, default='', verbose_name='Instructions'),
        ),
    ]
