# Generated by Django 4.2 on 2023-06-10 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TCCWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='description')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('advised', models.ManyToManyField(related_name='advised', to=settings.AUTH_USER_MODEL, verbose_name='advised')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='advisor', to=settings.AUTH_USER_MODEL, verbose_name='advisor')),
            ],
        ),
    ]
