# Generated by Django 4.2 on 2023-06-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstepversion',
            name='content',
            field=models.JSONField(blank=True, null=True, verbose_name='content'),
        ),
    ]
