# Generated by Django 4.2 on 2023-06-10 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0005_alter_step_presentation_date'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presented', models.BooleanField(default=False, verbose_name='presented')),
                ('status', models.SmallIntegerField(choices=[(0, 'assigned'), (1, 'pending'), (2, 'correction'), (3, 'adjusted'), (4, 'completed late'), (5, 'completed')], default=0, verbose_name='status')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='step', to='timetables.step', verbose_name='step')),
            ],
        ),
    ]
