# Generated by Django 4.2 on 2023-06-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalworkstage',
            name='status',
            field=models.IntegerField(choices=[(0, 'assigned'), (1, 'pending'), (2, 'correction'), (3, 'adjusted'), (4, 'completed late'), (5, 'completed'), (6, 'presented')], default=0, verbose_name='status'),
        ),
    ]
