# Generated by Django 4.2 on 2023-06-23 01:14

from django.db import migrations, models
import django.db.models.deletion
import uuid
import works.utils


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_finalworkstage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionContentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=works.utils.get_version_content_image_folder, verbose_name='image')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_images', to='works.finalworkversion', verbose_name='work version')),
            ],
        ),
    ]
