# Generated by Django 4.2 on 2023-07-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_versioncontentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalwork',
            name='approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='approved'),
        ),
    ]
