# Generated by Django 4.2 on 2023-07-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_alter_finalwork_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalwork',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
    ]
