# Generated by Django 4.2 on 2023-07-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_alter_changerequest_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalworkstage',
            name='status',
            field=models.IntegerField(choices=[(0, 'assigned'), (1, 'pending'), (2, 'correction'), (3, 'adjusted'), (4, 'completed late'), (5, 'completed'), (6, 'presented'), (7, 'under change'), (8, 'updated')], default=0, verbose_name='status'),
        ),
    ]
