# Generated by Django 4.2 on 2023-08-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_alter_finalworkstage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
    ]
