# Generated by Django 4.2 on 2023-08-20 01:31

from django.db import migrations
from django.utils import timezone


def populate_created_at(apps, schema_editor):
    FinalWork = apps.get_model('works', 'FinalWork')
    for instance in FinalWork.objects.all():
        instance.created_at = timezone.now()
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_finalwork_created_at'),
    ]

    operations = [
        migrations.RunPython(populate_created_at),
    ]
