# Generated by Django 4.2 on 2023-08-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_auto_20230819_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalworkversion',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed'),
        ),
    ]
