# Generated by Django 4.2 on 2023-09-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_finalwork_able_to_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalwork',
            name='able_to_present',
            field=models.BooleanField(default=None, null=True, verbose_name='able to present'),
        ),
    ]
