# Generated by Django 4.2 on 2023-10-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_alter_finalwork_able_to_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalwork',
            name='grading_score',
            field=models.SmallIntegerField(default=0, verbose_name='grading score'),
        ),
    ]
