# Generated by Django 4.2 on 2023-10-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0005_timetable_document_template'),
        ('works', '0015_finalwork_grading_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalwork',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timetable_works', to='timetables.timetable', verbose_name='timetable'),
        ),
    ]
