# Generated by Django 4.2 on 2023-10-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_finalwork_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalwork',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='approved'),
        ),
    ]
