# Generated by Django 4.2 on 2023-10-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_alter_finalwork_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalwork',
            name='title',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='title'),
        ),
    ]
