# Generated by Django 4.2 on 2023-10-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0018_finalwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalworkstage',
            name='status',
            field=models.IntegerField(choices=[(0, 'assigned'), (1, 'pending'), (2, 'correction'), (3, 'adjusted'), (4, 'completed late'), (5, 'completed'), (6, 'presented'), (7, 'under change'), (8, 'updated'), (9, 'presented_late'), (10, 'updated_late')], default=0, verbose_name='status'),
        ),
    ]
